QUESTIONS = {
  "tf-ch13": [
    {"q": "A garden maintained by people is an artificial ecosystem.", "q_pa": "ਲੋਕਾਂ ਦੁਆਰਾ ਸੰਭਾਲਿਆ ਗਿਆ ਬਾਗ਼ ਇੱਕ ਬਣਾਵਟੀ ਪਾਰਿਸਥਿਤਕੀ ਤੰਤਰ ਹੁੰਦਾ ਹੈ।", "answer": True,
     "explain": "Artificial ecosystems are made and maintained by humans, such as gardens and aquariums.", "explain_pa": "ਬਣਾਵਟੀ ਪਾਰਿਸਥਿਤਕੀ ਤੰਤਰ ਮਨੁੱਖ ਬਣਾਉਂਦੇ ਅਤੇ ਸੰਭਾਲਦੇ ਹਨ, ਜਿਵੇਂ ਬਾਗ਼ ਅਤੇ ਐਕੁਏਰੀਅਮ।"},
    {"q": "Abiotic components of an ecosystem include only animals.", "q_pa": "ਪਾਰਿਸਥਿਤਕੀ ਤੰਤਰ ਦੇ ਅਜੈਵਿਕ ਅੰਸ਼ਾਂ ਵਿੱਚ ਸਿਰਫ਼ ਜਾਨਵਰ ਸ਼ਾਮਲ ਹੁੰਦੇ ਹਨ।", "answer": False,
     "explain": "Abiotic components are non-living factors such as air, water, soil and temperature.", "explain_pa": "ਅਜੈਵਿਕ ਅੰਸ਼ ਹਵਾ, ਪਾਣੀ, ਮਿੱਟੀ ਅਤੇ ਤਾਪਮਾਨ ਵਰਗੇ ਨਿਰਜੀਵ ਘਟਕ ਹੁੰਦੇ ਹਨ।"},
    {"q": "A food web is a network of interconnected food chains.", "q_pa": "ਭੋਜਨ ਜਾਲ ਆਪਸ ਵਿੱਚ ਜੁੜੀਆਂ ਕਈ ਭੋਜਨ ਲੜੀਆਂ ਦਾ ਜਾਲ ਹੁੰਦਾ ਹੈ।", "answer": True,
     "explain": "Food webs form because organisms usually have more than one food source.", "explain_pa": "ਭੋਜਨ ਜਾਲ ਇਸ ਲਈ ਬਣਦੇ ਹਨ ਕਿਉਂਕਿ ਜੀਵਾਂ ਕੋਲ ਆਮ ਤੌਰ ਤੇ ਭੋਜਨ ਦੇ ਇੱਕ ਤੋਂ ਵੱਧ ਸਰੋਤ ਹੁੰਦੇ ਹਨ।"},
    {"q": "Most food chains can continue through unlimited trophic levels.", "q_pa": "ਜ਼ਿਆਦਾਤਰ ਭੋਜਨ ਲੜੀਆਂ ਬੇਅੰਤ ਪੋਸ਼ੀ ਪੱਧਰਾਂ ਤੱਕ ਚੱਲ ਸਕਦੀਆਂ ਹਨ।", "answer": False,
     "explain": "Food chains are usually short because much energy is lost at each transfer.", "explain_pa": "ਹਰ ਪੋਸ਼ੀ ਪੱਧਰ ਤੇ ਬਹੁਤ ਊਰਜਾ ਘਟ ਜਾਂਦੀ ਹੈ, ਇਸ ਲਈ ਭੋਜਨ ਲੜੀਆਂ ਆਮ ਤੌਰ ਤੇ ਛੋਟੀਆਂ ਹੁੰਦੀਆਂ ਹਨ।"},
    {"q": "Plants capture only a small part of the Sun's energy during photosynthesis.", "q_pa": "ਪੌਦੇ ਪ੍ਰਕਾਸ਼ ਸੰਸ਼ਲੇਸ਼ਣ ਦੌਰਾਨ ਸੂਰਜੀ ਊਰਜਾ ਦਾ ਕੇਵਲ ਛੋਟਾ ਹਿੱਸਾ ਫੜਦੇ ਹਨ।", "answer": True,
     "explain": "The deck states that producers capture about 1% of the Sun's energy to make food.", "explain_pa": "ਪਾਠ ਅਨੁਸਾਰ ਉਤਪਾਦਕ ਭੋਜਨ ਬਣਾਉਣ ਲਈ ਸੂਰਜੀ ਊਰਜਾ ਦਾ ਲਗਭਗ 1% ਹੀ ਫੜਦੇ ਹਨ।"},
    {"q": "In a food chain, arrows point from the eater to the organism being eaten.", "q_pa": "ਭੋਜਨ ਲੜੀ ਵਿੱਚ ਤੀਰ ਖਾਣ ਵਾਲੇ ਜੀਵ ਤੋਂ ਖਾਧੇ ਜਾ ਰਹੇ ਜੀਵ ਵੱਲ ਹੁੰਦੇ ਹਨ।", "answer": False,
     "explain": "Arrows show energy transfer, so they point from the food to the eater.", "explain_pa": "ਤੀਰ ਊਰਜਾ ਦੇ ਸੰਚਾਰ ਨੂੰ ਦਿਖਾਉਂਦੇ ਹਨ, ਇਸ ਲਈ ਇਹ ਭੋਜਨ ਤੋਂ ਖਾਣ ਵਾਲੇ ਜੀਵ ਵੱਲ ਹੁੰਦੇ ਹਨ।"},
    {"q": "DDT can enter water bodies and become more concentrated along a food chain.", "q_pa": "ਡੀ.ਡੀ.ਟੀ. ਜਲ ਸਰੋਤਾਂ ਵਿੱਚ ਜਾ ਕੇ ਭੋਜਨ ਲੜੀ ਵਿੱਚ ਅੱਗੇ ਵਧਦਿਆਂ ਹੋਰ ਸੰਕੇਂਦਰਿਤ ਹੋ ਸਕਦਾ ਹੈ।", "answer": True,
     "explain": "Non-biodegradable pesticides like DDT accumulate in organisms and increase at higher trophic levels.", "explain_pa": "ਡੀ.ਡੀ.ਟੀ. ਵਰਗੇ ਅਜੈਵ-ਵਿਘਟਨਸ਼ੀਲ ਕੀਟਨਾਸ਼ਕ ਜੀਵਾਂ ਵਿੱਚ ਇਕੱਠੇ ਹੋ ਕੇ ਉੱਚੇ ਪੋਸ਼ੀ ਪੱਧਰਾਂ ਤੇ ਵੱਧਦੇ ਹਨ।"},
    {"q": "Composting is mainly used for non-biodegradable plastic waste.", "q_pa": "ਕੰਪੋਸਟਿੰਗ ਮੁੱਖ ਤੌਰ ਤੇ ਅਜੈਵ-ਵਿਘਟਨਸ਼ੀਲ ਪਲਾਸਟਿਕ ਕਚਰੇ ਲਈ ਵਰਤੀ ਜਾਂਦੀ ਹੈ।", "answer": False,
     "explain": "Composting rots biodegradable waste into manure with the help of microbes.", "explain_pa": "ਕੰਪੋਸਟਿੰਗ ਵਿੱਚ ਸੂਖਮਜੀਵਾਂ ਦੀ ਮਦਦ ਨਾਲ ਜੈਵ-ਵਿਘਟਨਸ਼ੀਲ ਕਚਰਾ ਖਾਦ ਵਿੱਚ ਬਦਲਦਾ ਹੈ।"},
    {"q": "The Montreal Protocol helped reduce ozone-depleting CFC production.", "q_pa": "ਮਾਂਟਰੀਅਲ ਪ੍ਰੋਟੋਕਾਲ ਨੇ ਓਜ਼ੋਨ ਨੂੰ ਨੁਕਸਾਨ ਪਹੁੰਚਾਉਣ ਵਾਲੇ CFC ਉਤਪਾਦਨ ਨੂੰ ਘਟਾਉਣ ਵਿੱਚ ਮਦਦ ਕੀਤੀ।", "answer": True,
     "explain": "Countries agreed under the Montreal Protocol to phase out CFCs.", "explain_pa": "ਮਾਂਟਰੀਅਲ ਪ੍ਰੋਟੋਕਾਲ ਤਹਿਤ ਦੇਸ਼ਾਂ ਨੇ CFC ਨੂੰ ਹੌਲੀ-ਹੌਲੀ ਬੰਦ ਕਰਨ ਤੇ ਸਹਿਮਤੀ ਦਿੱਤੀ।"},
    {"q": "Incineration means storing rainwater for later use.", "q_pa": "ਇੰਸੀਨੇਰੇਸ਼ਨ ਦਾ ਅਰਥ ਹੈ ਮੀਂਹ ਦਾ ਪਾਣੀ ਬਾਅਦ ਲਈ ਸੰਭਾਲਣਾ।", "answer": False,
     "explain": "Incineration is the burning of waste at high temperature, not water storage.", "explain_pa": "ਇੰਸੀਨੇਰੇਸ਼ਨ ਕਚਰੇ ਨੂੰ ਉੱਚ ਤਾਪਮਾਨ ਤੇ ਸਾੜਨਾ ਹੈ, ਪਾਣੀ ਸੰਭਾਲਣਾ ਨਹੀਂ।"}
  ],
  "sib-ch13": [
    {"q": "What is a network of many food chains called?", "q_pa": "ਕਈ ਭੋਜਨ ਲੜੀਆਂ ਦੇ ਜਾਲ ਨੂੰ ਕੀ ਕਹਿੰਦੇ ਹਨ?",
     "a": "Food web", "a_pa": "ਭੋਜਨ ਜਾਲ", "explain": "A food web shows interconnected feeding relationships.", "explain_pa": "ਭੋਜਨ ਜਾਲ ਆਪਸ ਵਿੱਚ ਜੁੜੇ ਭੋਜਨ ਸੰਬੰਧ ਦਿਖਾਉਂਦਾ ਹੈ।"},
    {"q": "Which ecosystem type is an aquarium?", "q_pa": "ਐਕੁਏਰੀਅਮ ਕਿਸ ਕਿਸਮ ਦਾ ਪਾਰਿਸਥਿਤਕੀ ਤੰਤਰ ਹੈ?",
     "a": "Artificial", "a_pa": "ਬਣਾਵਟੀ", "explain": "An aquarium is made and maintained by humans.", "explain_pa": "ਐਕੁਏਰੀਅਮ ਮਨੁੱਖਾਂ ਦੁਆਰਾ ਬਣਾਇਆ ਤੇ ਸੰਭਾਲਿਆ ਜਾਂਦਾ ਹੈ।"},
    {"q": "What are non-living ecosystem factors called?", "q_pa": "ਪਾਰਿਸਥਿਤਕੀ ਤੰਤਰ ਦੇ ਨਿਰਜੀਵ ਘਟਕਾਂ ਨੂੰ ਕੀ ਕਹਿੰਦੇ ਹਨ?",
     "a": "Abiotic", "a_pa": "ਅਜੈਵਿਕ", "explain": "Air, water, soil and temperature are abiotic components.", "explain_pa": "ਹਵਾ, ਪਾਣੀ, ਮਿੱਟੀ ਅਤੇ ਤਾਪਮਾਨ ਅਜੈਵਿਕ ਅੰਸ਼ ਹਨ।"},
    {"q": "Which atom released from CFCs attacks ozone?", "q_pa": "CFC ਤੋਂ ਨਿਕਲਿਆ ਕਿਹੜਾ ਪਰਮਾਣੂ ਓਜ਼ੋਨ ਤੇ ਹਮਲਾ ਕਰਦਾ ਹੈ?",
     "a": "Chlorine", "a_pa": "ਕਲੋਰੀਨ", "explain": "UV light releases chlorine atoms from CFCs, and chlorine destroys ozone molecules.", "explain_pa": "UV ਰੌਸ਼ਨੀ CFC ਤੋਂ ਕਲੋਰੀਨ ਪਰਮਾਣੂ ਛੱਡਦੀ ਹੈ ਅਤੇ ਕਲੋਰੀਨ ਓਜ਼ੋਨ ਅਣੂਆਂ ਨੂੰ ਤੋੜਦੀ ਹੈ।"},
    {"q": "What waste-disposal method turns biodegradable waste into manure?", "q_pa": "ਕਿਹੜਾ ਕਚਰਾ ਨਿਪਟਾਰਾ ਤਰੀਕਾ ਜੈਵ-ਵਿਘਟਨਸ਼ੀਲ ਕਚਰੇ ਨੂੰ ਖਾਦ ਵਿੱਚ ਬਦਲਦਾ ਹੈ?",
     "a": "Composting", "a_pa": "ਕੰਪੋਸਟਿੰਗ", "explain": "Composting uses microbes to rot organic waste into useful manure.", "explain_pa": "ਕੰਪੋਸਟਿੰਗ ਸੂਖਮਜੀਵਾਂ ਨਾਲ ਜੈਵਿਕ ਕਚਰੇ ਨੂੰ ਲਾਭਦਾਇਕ ਖਾਦ ਵਿੱਚ ਬਦਲਦੀ ਹੈ।"},
    {"q": "What is waste burning at high temperature called?", "q_pa": "ਉੱਚ ਤਾਪਮਾਨ ਤੇ ਕਚਰਾ ਸਾੜਨ ਨੂੰ ਕੀ ਕਹਿੰਦੇ ਹਨ?",
     "a": "Incineration", "a_pa": "ਇੰਸੀਨੇਰੇਸ਼ਨ", "explain": "Incineration burns waste at high temperature, often for hospital waste.", "explain_pa": "ਇੰਸੀਨੇਰੇਸ਼ਨ ਵਿੱਚ ਕਚਰੇ ਨੂੰ ਉੱਚ ਤਾਪਮਾਨ ਤੇ ਸਾੜਿਆ ਜਾਂਦਾ ਹੈ, ਅਕਸਰ ਹਸਪਤਾਲੀ ਕਚਰੇ ਲਈ।"},
    {"q": "Which organisms first absorb DDT in a pond food chain?", "q_pa": "ਤਲਾਬ ਦੀ ਭੋਜਨ ਲੜੀ ਵਿੱਚ ਡੀ.ਡੀ.ਟੀ. ਸਭ ਤੋਂ ਪਹਿਲਾਂ ਕਿਹੜੇ ਜੀਵ ਸੋਖਦੇ ਹਨ?",
     "a": "Plankton", "a_pa": "ਪਲੈਂਕਟਨ", "explain": "The lesson shows microscopic producers, or plankton, absorbing DDT from pond water first.", "explain_pa": "ਪਾਠ ਵਿੱਚ ਸੂਖਮ ਉਤਪਾਦਕ ਪਲੈਂਕਟਨ ਤਲਾਬ ਦੇ ਪਾਣੀ ਤੋਂ ਸਭ ਤੋਂ ਪਹਿਲਾਂ ਡੀ.ਡੀ.ਟੀ. ਸੋਖਦੇ ਹਨ।"},
    {"q": "Which consumers eat producers directly?", "q_pa": "ਉਤਪਾਦਕਾਂ ਨੂੰ ਸਿੱਧਾ ਖਾਣ ਵਾਲੇ ਖਪਤਕਾਰ ਕਿਹੜੇ ਹੁੰਦੇ ਹਨ?",
     "a": "Primary consumers", "a_pa": "ਪ੍ਰਾਇਮਰੀ ਖਪਤਕਾਰ", "explain": "Primary consumers are herbivores that feed directly on producers.", "explain_pa": "ਪ੍ਰਾਇਮਰੀ ਖਪਤਕਾਰ ਸ਼ਾਕਾਹਾਰੀ ਹੁੰਦੇ ਹਨ ਜੋ ਉਤਪਾਦਕਾਂ ਨੂੰ ਸਿੱਧਾ ਖਾਂਦੇ ਹਨ।"},
    {"q": "Which waste-disposal method dumps waste in low-lying areas?", "q_pa": "ਕਿਹੜੇ ਨਿਪਟਾਰਾ ਤਰੀਕੇ ਵਿੱਚ ਕਚਰਾ ਨੀਵੀਆਂ ਥਾਵਾਂ ਵਿੱਚ ਪਾਇਆ ਜਾਂਦਾ ਹੈ?",
     "a": "Landfill", "a_pa": "ਲੈਂਡਫ਼ਿਲ", "explain": "Landfills place waste in low-lying areas and cover it with soil.", "explain_pa": "ਲੈਂਡਫ਼ਿਲ ਵਿੱਚ ਕਚਰਾ ਨੀਵੀਆਂ ਥਾਵਾਂ ਵਿੱਚ ਪਾ ਕੇ ਮਿੱਟੀ ਨਾਲ ਢੱਕਿਆ ਜਾਂਦਾ ਹੈ।"},
    {"q": "Which protocol banned CFC production worldwide?", "q_pa": "ਕਿਹੜੇ ਪ੍ਰੋਟੋਕਾਲ ਨੇ ਦੁਨੀਆ ਭਰ ਵਿੱਚ CFC ਉਤਪਾਦਨ ਤੇ ਰੋਕ ਲਗਾਈ?",
     "a": "Montreal Protocol", "a_pa": "ਮਾਂਟਰੀਅਲ ਪ੍ਰੋਟੋਕਾਲ", "explain": "The Montreal Protocol was the international agreement to phase out CFCs.", "explain_pa": "ਮਾਂਟਰੀਅਲ ਪ੍ਰੋਟੋਕਾਲ CFC ਨੂੰ ਹੌਲੀ-ਹੌਲੀ ਬੰਦ ਕਰਨ ਲਈ ਅੰਤਰਰਾਸ਼ਟਰੀ ਸਮਝੌਤਾ ਸੀ।"}
  ],
  "mcq-ch13": [
    {"q": "Which pair represents abiotic components?", "q_pa": "ਕਿਹੜੀ ਜੋੜੀ ਅਜੈਵਿਕ ਅੰਸ਼ ਦਰਸਾਉਂਦੀ ਹੈ?",
     "options": ["Air and water", "Grass and deer", "Bacteria and fungi"], "correct": 0,
     "explain": "Abiotic components are non-living factors like air and water.", "explain_pa": "ਅਜੈਵਿਕ ਅੰਸ਼ ਹਵਾ ਅਤੇ ਪਾਣੀ ਵਰਗੇ ਨਿਰਜੀਵ ਘਟਕ ਹੁੰਦੇ ਹਨ।"},
    {"q": "Why is a food web usually more stable than a single food chain?", "q_pa": "ਭੋਜਨ ਜਾਲ ਆਮ ਤੌਰ ਤੇ ਇਕੱਲੀ ਭੋਜਨ ਲੜੀ ਨਾਲੋਂ ਜ਼ਿਆਦਾ ਸਥਿਰ ਕਿਉਂ ਹੁੰਦਾ ਹੈ?",
     "options": ["It has no producers", "It gives alternative food paths", "It stops energy loss"], "correct": 1,
     "explain": "If one food source decreases, organisms in a food web may use other linked food sources.", "explain_pa": "ਜੇ ਇੱਕ ਭੋਜਨ ਸਰੋਤ ਘਟ ਜਾਵੇ ਤਾਂ ਭੋਜਨ ਜਾਲ ਵਿੱਚ ਜੀਵ ਹੋਰ ਜੁੜੇ ਸਰੋਤ ਵਰਤ ਸਕਦੇ ਹਨ।"},
    {"q": "In the chain grass → grasshopper → frog → snake, the frog is the:", "q_pa": "ਲੜੀ ਘਾਹ → ਟਿੱਡਾ → ਡੱਡੂ → ਸੱਪ ਵਿੱਚ ਡੱਡੂ ਕੀ ਹੈ?",
     "options": ["Producer", "Primary consumer", "Secondary consumer"], "correct": 2,
     "explain": "The frog eats the herbivore, so it is a secondary consumer.", "explain_pa": "ਡੱਡੂ ਸ਼ਾਕਾਹਾਰੀ ਟਿੱਡੇ ਨੂੰ ਖਾਂਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਦੂਜਾ ਖਪਤਕਾਰ ਹੈ।"},
    {"q": "If producers store 20,000 J, about how much reaches primary consumers?", "q_pa": "ਜੇ ਉਤਪਾਦਕ 20,000 J ਊਰਜਾ ਸੰਭਾਲਦੇ ਹਨ, ਤਾਂ ਪ੍ਰਾਇਮਰੀ ਖਪਤਕਾਰਾਂ ਤੱਕ ਲਗਭਗ ਕਿੰਨੀ ਊਰਜਾ ਪਹੁੰਚਦੀ ਹੈ?",
     "options": ["20,000 J", "2,000 J", "200 J"], "correct": 1,
     "explain": "By the 10% law, primary consumers receive about 10% of 20,000 J, which is 2,000 J.", "explain_pa": "10% ਦੇ ਨਿਯਮ ਅਨੁਸਾਰ ਪ੍ਰਾਇਮਰੀ ਖਪਤਕਾਰਾਂ ਨੂੰ 20,000 J ਦਾ ਲਗਭਗ 10%, ਅਰਥਾਤ 2,000 J ਮਿਲਦਾ ਹੈ।"},
    {"q": "Which item is biodegradable?", "q_pa": "ਕਿਹੜੀ ਵਸਤੂ ਜੈਵ-ਵਿਘਟਨਸ਼ੀਲ ਹੈ?",
     "options": ["Aluminium can", "Polythene bag", "Cotton cloth"], "correct": 2,
     "explain": "Cotton cloth can be broken down by microbes, unlike aluminium or polythene.", "explain_pa": "ਸੂਤੀ ਕੱਪੜਾ ਸੂਖਮਜੀਵਾਂ ਦੁਆਰਾ ਟੁੱਟ ਸਕਦਾ ਹੈ, ਪਰ ਐਲੂਮੀਨੀਅਮ ਜਾਂ ਪਾਲੀਥੀਨ ਨਹੀਂ।"},
    {"q": "Which action best shows reuse?", "q_pa": "ਕਿਹੜੀ ਕਿਰਿਆ ਮੁੜ ਵਰਤੋਂ ਨੂੰ ਸਭ ਤੋਂ ਵਧੀਆ ਦਿਖਾਉਂਦੀ ਹੈ?",
     "options": ["Refilling the same bottle", "Throwing a bottle away", "Burning all bottles"], "correct": 0,
     "explain": "Reuse means using the same item again without making a new product from it.", "explain_pa": "ਮੁੜ ਵਰਤੋਂ ਦਾ ਮਤਲਬ ਹੈ ਉਸੇ ਵਸਤੂ ਨੂੰ ਨਵਾਂ ਉਤਪਾਦ ਬਣਾਏ ਬਿਨਾਂ ਦੁਬਾਰਾ ਵਰਤਣਾ।"},
    {"q": "What happens when chlorine from CFCs reacts with ozone?", "q_pa": "ਜਦੋਂ CFC ਤੋਂ ਆਈ ਕਲੋਰੀਨ ਓਜ਼ੋਨ ਨਾਲ ਕ੍ਰਿਆ ਕਰਦੀ ਹੈ ਤਾਂ ਕੀ ਹੁੰਦਾ ਹੈ?",
     "options": ["Ozone molecules are destroyed", "More soil nutrients form", "Food webs become wider"], "correct": 0,
     "explain": "Chlorine acts in a chain reaction that breaks ozone into other oxygen compounds.", "explain_pa": "ਕਲੋਰੀਨ ਲੜੀਵਾਰ ਕ੍ਰਿਆ ਵਿੱਚ ਓਜ਼ੋਨ ਨੂੰ ਹੋਰ ਆਕਸੀਜਨ ਯੋਗਿਕਾਂ ਵਿੱਚ ਤੋੜ ਦਿੰਦੀ ਹੈ।"},
    {"q": "Which health problem can increase when more UV rays reach Earth?", "q_pa": "ਜਦੋਂ ਵਧੇਰੇ UV ਕਿਰਨਾਂ ਧਰਤੀ ਤੱਕ ਪਹੁੰਚਦੀਆਂ ਹਨ ਤਾਂ ਕਿਹੜੀ ਸਿਹਤ ਸਮੱਸਿਆ ਵੱਧ ਸਕਦੀ ਹੈ?",
     "options": ["Skin cancer", "Better immunity", "Faster composting"], "correct": 0,
     "explain": "Ozone depletion allows more UV radiation, which can cause skin cancer and cataracts.", "explain_pa": "ਓਜ਼ੋਨ ਘਟਣ ਨਾਲ ਵਧੇਰੇ UV ਰੇਡੀਏਸ਼ਨ ਆਉਂਦੀ ਹੈ, ਜਿਸ ਨਾਲ ਚਮੜੀ ਕੈਂਸਰ ਅਤੇ ਮੋਤੀਆਬਿੰਦ ਹੋ ਸਕਦੇ ਹਨ।"},
    {"q": "Which method cleans waste water before release?", "q_pa": "ਕਿਹੜਾ ਤਰੀਕਾ ਪਾਣੀ ਛੱਡਣ ਤੋਂ ਪਹਿਲਾਂ ਗੰਦੇ ਪਾਣੀ ਨੂੰ ਸਾਫ਼ ਕਰਦਾ ਹੈ?",
     "options": ["Sewage treatment", "Biomagnification", "Ozone depletion"], "correct": 0,
     "explain": "Sewage treatment removes pollutants from waste water before it is released.", "explain_pa": "ਸੀਵੇਜ ਟ੍ਰੀਟਮੈਂਟ ਪਾਣੀ ਛੱਡਣ ਤੋਂ ਪਹਿਲਾਂ ਗੰਦੇ ਪਾਣੀ ਵਿੱਚੋਂ ਪ੍ਰਦੂਸ਼ਕ ਹਟਾਉਂਦਾ ਹੈ।"},
    {"q": "Which statement about natural ecosystems is correct?", "q_pa": "ਕੁਦਰਤੀ ਪਾਰਿਸਥਿਤਕੀ ਤੰਤਰਾਂ ਬਾਰੇ ਕਿਹੜਾ ਕਥਨ ਸਹੀ ਹੈ?",
     "options": ["They are made only in laboratories", "They are self-regulating and made by nature", "They never contain abiotic factors"], "correct": 1,
     "explain": "Forests, ponds and grasslands are natural ecosystems that are made by nature and can regulate themselves.", "explain_pa": "ਜੰਗਲ, ਤਲਾਬ ਅਤੇ ਘਾਹਦਾਰ ਮੈਦਾਨ ਕੁਦਰਤ ਦੁਆਰਾ ਬਣੇ ਸਵੈ-ਨਿਯੰਤਰਿਤ ਪਾਰਿਸਥਿਤਕੀ ਤੰਤਰ ਹਨ।"}
  ],
  "tf-ch14": [
    {"q": "A good fuel should leave little smoke and ash.", "q_pa": "ਚੰਗਾ ਬਾਲਣ ਘੱਟ ਧੂੰਆਂ ਅਤੇ ਘੱਟ ਸੁਆਹ ਛੱਡਣਾ ਚਾਹੀਦਾ ਹੈ।", "answer": True,
     "explain": "Low pollution and little residue are important qualities of a good fuel.", "explain_pa": "ਘੱਟ ਪ੍ਰਦੂਸ਼ਣ ਅਤੇ ਘੱਟ ਬਚਿਆ ਪਦਾਰਥ ਚੰਗੇ ਬਾਲਣ ਦੇ ਮਹੱਤਵਪੂਰਨ ਗੁਣ ਹਨ।"},
    {"q": "In a thermal power plant, steam turns a turbine before electricity is generated.", "q_pa": "ਥਰਮਲ ਪਾਵਰ ਪਲਾਂਟ ਵਿੱਚ ਬਿਜਲੀ ਬਣਨ ਤੋਂ ਪਹਿਲਾਂ ਭਾਫ਼ ਟਰਬਾਈਨ ਨੂੰ ਘੁਮਾਉਂਦੀ ਹੈ।", "answer": True,
     "explain": "Heat makes steam, steam spins the turbine, and the generator produces electricity.", "explain_pa": "ਗਰਮੀ ਭਾਫ਼ ਬਣਾਉਂਦੀ ਹੈ, ਭਾਫ਼ ਟਰਬਾਈਨ ਘੁਮਾਉਂਦੀ ਹੈ ਅਤੇ ਜਨਰੇਟਰ ਬਿਜਲੀ ਬਣਾਉਂਦਾ ਹੈ।"},
    {"q": "Biomass and wind energy are listed under conventional sources in NCERT Class 10.", "q_pa": "NCERT ਕਲਾਸ 10 ਵਿੱਚ ਬਾਇਓਮਾਸ ਅਤੇ ਪੌਣ ਊਰਜਾ ਨੂੰ ਪਰੰਪਰਾਗਤ ਸਰੋਤਾਂ ਹੇਠ ਰੱਖਿਆ ਗਿਆ ਹੈ।", "answer": True,
     "explain": "NCERT discusses improved use of biomass and wind energy within conventional sources.", "explain_pa": "NCERT ਬਾਇਓਮਾਸ ਅਤੇ ਪੌਣ ਊਰਜਾ ਦੀ ਸੁਧਰੀ ਵਰਤੋਂ ਨੂੰ ਪਰੰਪਰਾਗਤ ਸਰੋਤਾਂ ਵਿੱਚ ਚਰਚਾ ਕਰਦਾ ਹੈ।"},
    {"q": "A solar cooker works equally well at night.", "q_pa": "ਸੋਲਰ ਕੁੱਕਰ ਰਾਤ ਨੂੰ ਵੀ ਉਤਨਾ ਹੀ ਵਧੀਆ ਕੰਮ ਕਰਦਾ ਹੈ।", "answer": False,
     "explain": "Solar cookers need sunlight, so they do not work well at night or in rain.", "explain_pa": "ਸੋਲਰ ਕੁੱਕਰ ਨੂੰ ਸੂਰਜੀ ਰੌਸ਼ਨੀ ਚਾਹੀਦੀ ਹੈ, ਇਸ ਲਈ ਇਹ ਰਾਤ ਜਾਂ ਮੀਂਹ ਵਿੱਚ ਚੰਗਾ ਕੰਮ ਨਹੀਂ ਕਰਦਾ।"},
    {"q": "Geothermal energy is available everywhere in equal amounts.", "q_pa": "ਭੂ-ਤਾਪੀ ਊਰਜਾ ਹਰ ਥਾਂ ਇੱਕੋ ਜਿਹੀ ਮਾਤਰਾ ਵਿੱਚ ਮਿਲਦੀ ਹੈ।", "answer": False,
     "explain": "Geothermal energy is practical mainly in places with hot rocks, hot springs or volcanic activity.", "explain_pa": "ਭੂ-ਤਾਪੀ ਊਰਜਾ ਮੁੱਖ ਤੌਰ ਤੇ ਗਰਮ ਚੱਟਾਨਾਂ, ਗਰਮ ਚਸ਼ਮਿਆਂ ਜਾਂ ਜਵਾਲਾਮੁਖੀ ਖੇਤਰਾਂ ਵਿੱਚ ਲਾਭਕਾਰੀ ਹੁੰਦੀ ਹੈ।"},
    {"q": "Nuclear fission produces energy by joining two light nuclei together.", "q_pa": "ਨਿਊਕਲੀ ਵਿਖੰਡਨ ਦੋ ਹਲਕੇ ਨਿਊਕਲੀਅਸਾਂ ਨੂੰ ਜੋੜ ਕੇ ਊਰਜਾ ਪੈਦਾ ਕਰਦਾ ਹੈ।", "answer": False,
     "explain": "Fission releases energy when a heavy nucleus such as uranium splits.", "explain_pa": "ਵਿਖੰਡਨ ਵਿੱਚ ਯੂਰੇਨੀਅਮ ਵਰਗਾ ਭਾਰੀ ਨਿਊਕਲੀਅਸ ਟੁੱਟਦਾ ਹੈ ਅਤੇ ਊਰਜਾ ਨਿਕਲਦੀ ਹੈ।"}
  ],
  "sib-ch14": [
    {"q": "Which value measures heat from a unit amount of fuel?", "q_pa": "ਬਾਲਣ ਦੀ ਇਕਾਈ ਮਾਤਰਾ ਤੋਂ ਮਿਲਣ ਵਾਲੀ ਗਰਮੀ ਨੂੰ ਕਿਹੜਾ ਮੁੱਲ ਮਾਪਦਾ ਹੈ?",
     "a": "Calorific value", "a_pa": "ਊਸ਼ਮੀ ਮੁੱਲ", "explain": "Calorific value tells how much heat a fuel gives per unit amount.", "explain_pa": "ਊਸ਼ਮੀ ਮੁੱਲ ਦੱਸਦਾ ਹੈ ਕਿ ਬਾਲਣ ਦੀ ਇਕਾਈ ਮਾਤਰਾ ਕਿੰਨੀ ਗਰਮੀ ਦਿੰਦੀ ਹੈ।"},
    {"q": "Which device converts mechanical energy into electrical energy in a power plant?", "q_pa": "ਪਾਵਰ ਪਲਾਂਟ ਵਿੱਚ ਮਕੈਨਿਕਲ ਊਰਜਾ ਨੂੰ ਬਿਜਲੀ ਊਰਜਾ ਵਿੱਚ ਕਿਹੜਾ ਯੰਤਰ ਬਦਲਦਾ ਹੈ?",
     "a": "Generator", "a_pa": "ਜਨਰੇਟਰ", "explain": "After a turbine spins, the generator converts that motion into electricity.", "explain_pa": "ਟਰਬਾਈਨ ਦੇ ਘੁੰਮਣ ਤੋਂ ਬਾਅਦ ਜਨਰੇਟਰ ਉਸ ਗਤੀ ਨੂੰ ਬਿਜਲੀ ਵਿੱਚ ਬਦਲਦਾ ਹੈ।"},
    {"q": "What type of digestion produces biogas?", "q_pa": "ਕਿਸ ਕਿਸਮ ਦਾ ਵਿਘਟਨ ਬਾਇਓਗੈਸ ਬਣਾਉਂਦਾ ਹੈ?",
     "a": "Anaerobic", "a_pa": "ਅਨਾਔਕਸੀ", "explain": "Biogas forms when organic waste decomposes without oxygen.", "explain_pa": "ਜੈਵਿਕ ਕਚਰਾ ਆਕਸੀਜਨ ਤੋਂ ਬਿਨਾਂ ਵਿਘਟਿਤ ਹੋਵੇ ਤਾਂ ਬਾਇਓਗੈਸ ਬਣਦੀ ਹੈ।"},
    {"q": "Which solar-cell material is costly to manufacture?", "q_pa": "ਸੋਲਰ ਸੈੱਲਾਂ ਦੀ ਕਿਹੜੀ ਸਮੱਗਰੀ ਬਣਾਉਣ ਵਿੱਚ ਮਹਿੰਗੀ ਹੁੰਦੀ ਹੈ?",
     "a": "Silicon", "a_pa": "ਸਿਲਿਕਾਨ", "explain": "The deck notes that silicon solar cells are expensive to manufacture.", "explain_pa": "ਪਾਠ ਦੱਸਦਾ ਹੈ ਕਿ ਸਿਲਿਕਾਨ ਵਾਲੇ ਸੋਲਰ ਸੈੱਲ ਬਣਾਉਣ ਮਹਿੰਗੇ ਹੁੰਦੇ ਹਨ।"},
    {"q": "Which sea-energy method uses warm surface and cold deep water?", "q_pa": "ਕਿਹੜਾ ਸਮੁੰਦਰੀ ਊਰਜਾ ਤਰੀਕਾ ਗਰਮ ਸਤ੍ਹਾ ਅਤੇ ਠੰਢੇ ਗਹਿਰੇ ਪਾਣੀ ਨੂੰ ਵਰਤਦਾ ਹੈ?",
     "a": "OTEC", "a_pa": "ਓਟੈਕ", "explain": "OTEC uses the temperature difference between warm surface water and cold deep water.", "explain_pa": "ਓਟੈਕ ਗਰਮ ਸਤ੍ਹਾਈ ਪਾਣੀ ਅਤੇ ਠੰਢੇ ਗਹਿਰੇ ਪਾਣੀ ਦੇ ਤਾਪਮਾਨ ਅੰਤਰ ਨੂੰ ਵਰਤਦਾ ਹੈ।"},
    {"q": "Which fuel burns to form water as the main product?", "q_pa": "ਕਿਹੜਾ ਬਾਲਣ ਸੜ ਕੇ ਮੁੱਖ ਉਤਪਾਦ ਵਜੋਂ ਪਾਣੀ ਬਣਾਉਂਦਾ ਹੈ?",
     "a": "Hydrogen", "a_pa": "ਹਾਈਡ੍ਰੋਜਨ", "explain": "Hydrogen combines with oxygen during combustion to produce water and energy.", "explain_pa": "ਹਾਈਡ੍ਰੋਜਨ ਦਹਿਨ ਦੌਰਾਨ ਆਕਸੀਜਨ ਨਾਲ ਮਿਲ ਕੇ ਪਾਣੀ ਅਤੇ ਊਰਜਾ ਬਣਾਉਂਦਾ ਹੈ।"}
  ],
  "mcq-ch14": [
    {"q": "Which sequence best describes a thermal power plant?", "q_pa": "ਕਿਹੜਾ ਕ੍ਰਮ ਥਰਮਲ ਪਾਵਰ ਪਲਾਂਟ ਨੂੰ ਸਭ ਤੋਂ ਵਧੀਆ ਦਰਸਾਉਂਦਾ ਹੈ?",
     "options": ["Fuel burns → steam → turbine → generator", "Sunlight → solar cell → steam → dam", "Wind → boiler → coal → battery"], "correct": 0,
     "explain": "Thermal plants burn fuel to make steam that turns turbines connected to generators.", "explain_pa": "ਥਰਮਲ ਪਲਾਂਟ ਬਾਲਣ ਸਾੜ ਕੇ ਭਾਫ਼ ਬਣਾਉਂਦੇ ਹਨ ਜੋ ਜਨਰੇਟਰ ਨਾਲ ਜੁੜੀਆਂ ਟਰਬਾਈਨਾਂ ਨੂੰ ਘੁਮਾਉਂਦੀ ਹੈ।"},
    {"q": "Which source is most suitable for a farming village with plenty of cow dung?", "q_pa": "ਬਹੁਤ ਸਾਰੇ ਗੋਬਰ ਵਾਲੇ ਖੇਤੀਬਾੜੀ ਪਿੰਡ ਲਈ ਕਿਹੜਾ ਸਰੋਤ ਸਭ ਤੋਂ ਉਚਿਤ ਹੈ?",
     "options": ["Tidal energy", "Biogas", "Geothermal energy"], "correct": 1,
     "explain": "A biogas plant uses dung slurry to make methane-rich fuel and manure.", "explain_pa": "ਬਾਇਓਗੈਸ ਪਲਾਂਟ ਗੋਬਰ ਦੀ ਸਲਰੀ ਤੋਂ ਮੀਥੇਨ-ਭਰਪੂਰ ਬਾਲਣ ਅਤੇ ਖਾਦ ਬਣਾਉਂਦਾ ਹੈ।"},
    {"q": "Which is a major concern of nuclear power?", "q_pa": "ਪ੍ਰਮਾਣੂ ਊਰਜਾ ਦੀ ਇੱਕ ਵੱਡੀ ਚਿੰਤਾ ਕਿਹੜੀ ਹੈ?",
     "options": ["Radioactive waste", "No energy output", "No fuel needed"], "correct": 0,
     "explain": "Nuclear power has high output, but its radioactive waste must be stored safely.", "explain_pa": "ਪ੍ਰਮਾਣੂ ਊਰਜਾ ਵੱਡੀ ਮਾਤਰਾ ਵਿੱਚ ਊਰਜਾ ਦਿੰਦੀ ਹੈ, ਪਰ ਇਸ ਦਾ ਰੇਡੀਓਐਕਟਿਵ ਕਚਰਾ ਸੁਰੱਖਿਅਤ ਰੱਖਣਾ ਪੈਂਦਾ ਹੈ।"},
    {"q": "Which condition is most important for wind farms?", "q_pa": "ਪੌਣ ਚੱਕੀਆਂ ਲਈ ਕਿਹੜੀ ਹਾਲਤ ਸਭ ਤੋਂ ਜ਼ਰੂਰੀ ਹੈ?",
     "options": ["Deep ocean water", "Strong steady wind", "Radioactive fuel"], "correct": 1,
     "explain": "Wind turbines need reliable wind speed, usually in coastal or open windy areas.", "explain_pa": "ਪੌਣ ਟਰਬਾਈਨਾਂ ਨੂੰ ਭਰੋਸੇਯੋਗ ਹਵਾ ਦੀ ਗਤੀ ਚਾਹੀਦੀ ਹੈ, ਆਮ ਤੌਰ ਤੇ ਤੱਟੀ ਜਾਂ ਖੁੱਲ੍ਹੇ ਹਵਾਦਾਰ ਖੇਤਰਾਂ ਵਿੱਚ।"},
    {"q": "Which pair is non-renewable on a human time scale?", "q_pa": "ਮਨੁੱਖੀ ਸਮੇਂ ਦੇ ਪੱਧਰ ਤੇ ਕਿਹੜੀ ਜੋੜੀ ਨਾ-ਨਵਿਆਉਣਯੋਗ ਹੈ?",
     "options": ["Solar and wind", "Coal and petroleum", "Biogas and water"], "correct": 1,
     "explain": "Coal and petroleum are fossil fuels that take millions of years to form.", "explain_pa": "ਕੋਲਾ ਅਤੇ ਪੈਟਰੋਲੀਅਮ ਪਥਰਾਟ ਬਾਲਣ ਹਨ ਜੋ ਬਣਨ ਵਿੱਚ ਲੱਖਾਂ ਸਾਲ ਲੈਂਦੇ ਹਨ।"}
  ],
  "tf-ch16": [
    {"q": "Refusing unnecessary single-use items can prevent waste before it is created.", "q_pa": "ਬੇਲੋੜੀਆਂ ਇਕ-ਵਾਰ ਵਰਤੋਂ ਵਾਲੀਆਂ ਵਸਤੂਆਂ ਤੋਂ ਇਨਕਾਰ ਕਰਨਾ ਕਚਰਾ ਬਣਨ ਤੋਂ ਪਹਿਲਾਂ ਹੀ ਰੋਕ ਸਕਦਾ ਹੈ।", "answer": True,
     "explain": "Refuse comes early in the 5 R's because it avoids waste at the source.", "explain_pa": "Refuse 5 R's ਵਿੱਚ ਸ਼ੁਰੂ ਦਾ ਕਦਮ ਹੈ ਕਿਉਂਕਿ ਇਹ ਸਰੋਤ ਤੇ ਹੀ ਕਚਰਾ ਰੋਕਦਾ ਹੈ।"},
    {"q": "Industrialists are one of the stakeholders in forest conservation.", "q_pa": "ਉਦਯੋਗਪਤੀ ਜੰਗਲ ਸੰਰੱਖਣ ਦੇ ਹਿੱਸੇਦਾਰਾਂ ਵਿੱਚੋਂ ਇੱਕ ਹਨ।", "answer": True,
     "explain": "Stakeholders include local people, the forest department, industrialists and wildlife enthusiasts.", "explain_pa": "ਹਿੱਸੇਦਾਰਾਂ ਵਿੱਚ ਸਥਾਨਕ ਲੋਕ, ਜੰਗਲਾਤ ਵਿਭਾਗ, ਉਦਯੋਗਪਤੀ ਅਤੇ ਵਨਜੀਵ ਪ੍ਰੇਮੀ ਸ਼ਾਮਲ ਹਨ।"},
    {"q": "Water harvesting helps recharge groundwater.", "q_pa": "ਪਾਣੀ ਸੰਭਾਲ ਧਰਤੀ ਹੇਠਲੇ ਪਾਣੀ ਨੂੰ ਮੁੜ ਭਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦੀ ਹੈ।", "answer": True,
     "explain": "Capturing rainwater slows runoff and allows water to soak into the ground.", "explain_pa": "ਮੀਂਹ ਦੇ ਪਾਣੀ ਨੂੰ ਰੋਕਣ ਨਾਲ ਬਹਾਅ ਹੌਲਾ ਹੁੰਦਾ ਹੈ ਅਤੇ ਪਾਣੀ ਜ਼ਮੀਨ ਵਿੱਚ ਸਮਾ ਕੇ ਭੂਜਲ ਭਰਦਾ ਹੈ।"},
    {"q": "Forests are useful only because they provide timber.", "q_pa": "ਜੰਗਲ ਸਿਰਫ਼ ਇਸ ਲਈ ਲਾਭਦਾਇਕ ਹਨ ਕਿਉਂਕਿ ਉਹ ਲੱਕੜ ਦਿੰਦੇ ਹਨ।", "answer": False,
     "explain": "Forests also protect soil, support rainfall, maintain biodiversity and support livelihoods.", "explain_pa": "ਜੰਗਲ ਮਿੱਟੀ ਦੀ ਰੱਖਿਆ ਕਰਦੇ, ਵਰਖਾ ਨੂੰ ਸਹਾਰਾ ਦਿੰਦੇ, ਜੀਵ-ਵਿਭਿੰਨਤਾ ਬਚਾਉਂਦੇ ਅਤੇ ਰੋਜ਼ੀ-ਰੋਟੀ ਨੂੰ ਸਹਾਰਾ ਦਿੰਦੇ ਹਨ।"},
    {"q": "Siltation can increase the useful life of large dams.", "q_pa": "ਗਾਦ ਜਮਣਾ ਵੱਡੇ ਬੰਨ੍ਹਾਂ ਦੀ ਲਾਭਕਾਰੀ ਉਮਰ ਵਧਾ ਸਕਦਾ ਹੈ।", "answer": False,
     "explain": "The deck lists siltation as an economic problem because it reduces dam life.", "explain_pa": "ਪਾਠ ਗਾਦ ਜਮਣ ਨੂੰ ਆਰਥਿਕ ਸਮੱਸਿਆ ਦੱਸਦਾ ਹੈ ਕਿਉਂਕਿ ਇਹ ਬੰਨ੍ਹ ਦੀ ਉਮਰ ਘਟਾਉਂਦਾ ਹੈ।"},
    {"q": "Burning coal and petroleum does not release carbon dioxide.", "q_pa": "ਕੋਲਾ ਅਤੇ ਪੈਟਰੋਲੀਅਮ ਸਾੜਨ ਨਾਲ ਕਾਰਬਨ ਡਾਈਆਕਸਾਈਡ ਨਹੀਂ ਨਿਕਲਦੀ।", "answer": False,
     "explain": "Burning fossil fuels releases air pollutants and CO₂.", "explain_pa": "ਪਥਰਾਟ ਬਾਲਣ ਸਾੜਨ ਨਾਲ ਹਵਾ ਪ੍ਰਦੂਸ਼ਕ ਅਤੇ CO₂ ਨਿਕਲਦੇ ਹਨ।"}
  ],
  "sib-ch16": [
    {"q": "Which R means avoiding unnecessary items?", "q_pa": "ਕਿਹੜਾ R ਬੇਲੋੜੀਆਂ ਵਸਤੂਆਂ ਤੋਂ ਇਨਕਾਰ ਕਰਨ ਲਈ ਹੈ?",
     "a": "Refuse", "a_pa": "ਇਨਕਾਰ", "explain": "Refuse means saying no to things like single-use plastic when they are not needed.", "explain_pa": "Refuse ਦਾ ਅਰਥ ਹੈ ਬੇਲੋੜੀਆਂ ਇਕ-ਵਾਰ ਵਰਤੋਂ ਵਾਲੀਆਂ ਪਲਾਸਟਿਕ ਵਸਤੂਆਂ ਨੂੰ ਨਾ ਕਹਿਣਾ।"},
    {"q": "Who hugged trees during the Chipko movement?", "q_pa": "ਚਿਪਕੋ ਅੰਦੋਲਨ ਦੌਰਾਨ ਰੁੱਖਾਂ ਨੂੰ ਕਿਸ ਨੇ ਜੱਫੀ ਪਾਈ?",
     "a": "Villagers", "a_pa": "ਪਿੰਡ ਵਾਸੀਆਂ", "explain": "Villagers, especially women, hugged trees to stop contractors from cutting them.", "explain_pa": "ਪਿੰਡ ਵਾਸੀਆਂ, ਖ਼ਾਸ ਕਰ ਔਰਤਾਂ ਨੇ ਠੇਕੇਦਾਰਾਂ ਨੂੰ ਰੁੱਖ ਕੱਟਣ ਤੋਂ ਰੋਕਣ ਲਈ ਰੁੱਖਾਂ ਨੂੰ ਜੱਫੀ ਪਾਈ।"},
    {"q": "Which Rajasthan community protects trees and animals?", "q_pa": "ਰਾਜਸਥਾਨ ਦੀ ਕਿਹੜੀ ਬਰਾਦਰੀ ਰੁੱਖਾਂ ਅਤੇ ਜਾਨਵਰਾਂ ਦੀ ਰੱਖਿਆ ਕਰਦੀ ਹੈ?",
     "a": "Bishnoi", "a_pa": "ਬਿਸ਼ਨੋਈ", "explain": "The Bishnoi community is known for protecting trees and wildlife.", "explain_pa": "ਬਿਸ਼ਨੋਈ ਬਰਾਦਰੀ ਰੁੱਖਾਂ ਅਤੇ ਵਨਜੀਵਾਂ ਦੀ ਰੱਖਿਆ ਲਈ ਜਾਣੀ ਜਾਂਦੀ ਹੈ।"},
    {"q": "Which trees did Amrita Devi Bishnoi protect?", "q_pa": "ਅੰਮ੍ਰਿਤਾ ਦੇਵੀ ਬਿਸ਼ਨੋਈ ਨੇ ਕਿਹੜੇ ਰੁੱਖਾਂ ਦੀ ਰੱਖਿਆ ਕੀਤੀ?",
     "a": "Khejri trees", "a_pa": "ਖੇਜੜੀ ਰੁੱਖ", "explain": "Amrita Devi Bishnoi is remembered for sacrificing her life to protect Khejri trees.", "explain_pa": "ਅੰਮ੍ਰਿਤਾ ਦੇਵੀ ਬਿਸ਼ਨੋਈ ਨੂੰ ਖੇਜੜੀ ਰੁੱਖਾਂ ਦੀ ਰੱਖਿਆ ਲਈ ਜੀਵਨ ਨਿਛਾਵਰ ਕਰਨ ਕਰਕੇ ਯਾਦ ਕੀਤਾ ਜਾਂਦਾ ਹੈ।"},
    {"q": "What small earthen check dam recharges groundwater?", "q_pa": "ਧਰਤੀ ਹੇਠਲਾ ਪਾਣੀ ਭਰਨ ਵਾਲਾ ਛੋਟਾ ਮਿੱਟੀ ਦਾ ਚੈਕ ਡੈਮ ਕੀ ਹੈ?",
     "a": "Johad", "a_pa": "ਜੋਹੜ", "explain": "A johad is a traditional small earthen check dam used to recharge groundwater.", "explain_pa": "ਜੋਹੜ ਧਰਤੀ ਹੇਠਲਾ ਪਾਣੀ ਭਰਨ ਲਈ ਵਰਤਿਆ ਜਾਣ ਵਾਲਾ ਪਰੰਪਰਾਗਤ ਛੋਟਾ ਮਿੱਟੀ ਦਾ ਚੈਕ ਡੈਮ ਹੈ।"},
    {"q": "Which fossil fuel gives petrol and diesel?", "q_pa": "ਕਿਹੜਾ ਪਥਰਾਟ ਬਾਲਣ ਪੈਟਰੋਲ ਅਤੇ ਡੀਜ਼ਲ ਦਿੰਦਾ ਹੈ?",
     "a": "Petroleum", "a_pa": "ਪੈਟਰੋਲੀਅਮ", "explain": "Petroleum is refined to obtain fuels such as petrol, diesel, kerosene and LPG.", "explain_pa": "ਪੈਟਰੋਲੀਅਮ ਨੂੰ ਸ਼ੁੱਧ ਕਰਕੇ ਪੈਟਰੋਲ, ਡੀਜ਼ਲ, ਮਿੱਟੀ ਦਾ ਤੇਲ ਅਤੇ LPG ਵਰਗੇ ਬਾਲਣ ਮਿਲਦੇ ਹਨ।"}
  ],
  "mcq-ch16": [
    {"q": "Which option is an example of repurpose?", "q_pa": "ਕਿਹੜੀ ਚੋਣ repurpose ਦੀ ਉਦਾਹਰਨ ਹੈ?",
     "options": ["Use an old jar as a planter", "Leave taps running", "Cut forests for wasteful use"], "correct": 0,
     "explain": "Repurpose means using an old item for a new purpose.", "explain_pa": "Repurpose ਦਾ ਮਤਲਬ ਹੈ ਪੁਰਾਣੀ ਵਸਤੂ ਨੂੰ ਨਵੇਂ ਮਕਸਦ ਲਈ ਵਰਤਣਾ।"},
    {"q": "Why should local people be included in forest management?", "q_pa": "ਜੰਗਲ ਪ੍ਰਬੰਧਨ ਵਿੱਚ ਸਥਾਨਕ ਲੋਕਾਂ ਨੂੰ ਕਿਉਂ ਸ਼ਾਮਲ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ?",
     "options": ["They never use forest products", "They depend on forests daily", "They only build large dams"], "correct": 1,
     "explain": "Local communities need fuelwood, fodder and small forest products, so their participation improves conservation.", "explain_pa": "ਸਥਾਨਕ ਲੋਕਾਂ ਨੂੰ ਇੰਧਨ ਲੱਕੜੀ, ਚਾਰਾ ਅਤੇ ਛੋਟੇ ਜੰਗਲੀ ਉਤਪਾਦ ਚਾਹੀਦੇ ਹਨ, ਇਸ ਲਈ ਉਨ੍ਹਾਂ ਦੀ ਭਾਗੀਦਾਰੀ ਸੰਰੱਖਣ ਸੁਧਾਰਦੀ ਹੈ।"},
    {"q": "Which is a benefit of dams?", "q_pa": "ਬੰਨ੍ਹਾਂ ਦਾ ਇੱਕ ਲਾਭ ਕਿਹੜਾ ਹੈ?",
     "options": ["They always have no cost", "They never affect habitats", "They store water for irrigation"], "correct": 2,
     "explain": "Dams can store water for irrigation and drinking and can generate hydroelectricity.", "explain_pa": "ਬੰਨ੍ਹ ਸਿੰਚਾਈ ਅਤੇ ਪੀਣ ਲਈ ਪਾਣੀ ਸੰਭਾਲ ਸਕਦੇ ਹਨ ਅਤੇ ਜਲ-ਬਿਜਲੀ ਬਣਾ ਸਕਦੇ ਹਨ।"},
    {"q": "Which practice directly reduces petroleum use?", "q_pa": "ਕਿਹੜੀ ਆਦਤ ਪੈਟਰੋਲੀਅਮ ਦੀ ਵਰਤੋਂ ਸਿੱਧੀ ਘਟਾਉਂਦੀ ਹੈ?",
     "options": ["Using public transport", "Leaving engines idling", "Wasting diesel"], "correct": 0,
     "explain": "Public transport or carpooling reduces fuel consumption per person.", "explain_pa": "ਜਨਤਕ ਆਵਾਜਾਈ ਜਾਂ ਕਾਰਪੂਲਿੰਗ ਪ੍ਰਤੀ ਵਿਅਕਤੀ ਬਾਲਣ ਦੀ ਖਪਤ ਘਟਾਉਂਦੀ ਹੈ।"},
    {"q": "What does watershed management conserve together?", "q_pa": "ਵਾਟਰਸ਼ੈੱਡ ਪ੍ਰਬੰਧਨ ਇਕੱਠੇ ਕੀ ਸੰਭਾਲਦਾ ਹੈ?",
     "options": ["Plastic and smoke", "Soil and water", "Coal and uranium"], "correct": 1,
     "explain": "Watershed management slows runoff, protects soil and recharges groundwater.", "explain_pa": "ਵਾਟਰਸ਼ੈੱਡ ਪ੍ਰਬੰਧਨ ਬਹਾਅ ਹੌਲਾ ਕਰਦਾ, ਮਿੱਟੀ ਬਚਾਉਂਦਾ ਅਤੇ ਭੂਜਲ ਭਰਦਾ ਹੈ।"}
  ]
}
